version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - '3000'
    links:
      - tasks-mongo-db
    depends_on:
      - tasks-mongo-db
  ui:
    container_name: ui
    build: ./ui
    depends_on:
      - backend
    links:
      - backend
    ports:
    - '80:80'
  tasks-mongo-db:
    container_name: tasks-mongo-db
    image: mongo
    volumes:
      - ./etc/mongo/db:/data/db
